### ISSUE TITLE
fix: FluentTreeView is not working in Maui Blazer

### ISSUE THREAD

**Issue by yayayayuyuyu** [microsoft/fast-blazor#351] opened 2023-03-20 10:42 UTC
# 🐛 Bug Report

SelectedChanged and ExpandedChanged events for FluentTreeView are not firing in Maui Blazor.
Blazor Wasm and Blazor Server work fine.

## 💻 Repro or Code Sample

1.Create a new Maui Blazor project on VS2022mac
2.Prepare to use fast-blazor (https://github.com/microsoft/fast-blazor/blob/main/README.md)
3. Copy the sample demo page to Index.razor ("Default with event handling" at https://brave-cliff-0c0c93310.azurestaticapps.net/TreeView)

In Blazor Wasm and Blazor Server, the behavior is the same as in the demo page (text changes according to the selected node), but in Maui Blazor, the text does not change.

## 🌍 Your Environment

* OS & Device: [MacOS 12.6, iOS16] on [iPhone13, m1mac]
* Browser [Google Chrome, Apple Safari]
* .NET6 or 7 and FAST Version 2.1.3

**Comment by vnbaaij** [comment] 2023-03-20 11:15
Duplicate of #327

**Closed by vnbaaij** 2023-03-20 11:15 UTC

**Comment by lkd3063601** [comment] 2023-03-24 02:40
I have the same problem
