### ISSUE TITLE
fix: The "FluentTextField"'s OnBlur event is never raised

### ISSUE THREAD

**Issue by mafei1982** [microsoft/fast-blazor#181] opened 2022-04-27 02:18 UTC
# 🐛 Bug Report
I use `FluentTextField` in my project and try to use `onblur` event. But the event is never raised. Now I am using 'onfocusout` instead

## 💻 Repro or Code Sample

```
<FluentTextField @bind-Value=@_text
                     Disabled=@ReadOnly
                     @onblur=@(_ => ViewModel.Value = _text)
                     class=@(_textFieldCssClasses) />
```

## 🤔 Expected Behavior
The onblur event should work for `FluentTextField`

## 😯 Current Behavior
The onblur event is never raised for `FluentTextField`. I guess someone forgot to pass the internal `onblur` event to the parent container

## 🌍 Your Environment

* OS & Device: [e.g. MacOS, iOS, Windows, Linux] on [iPhone 7, PC]
* Browser [e.g. Microsoft Edge, Google Chrome, Apple Safari, Mozilla FireFox]
* .NET and FAST Version [e.g. 1.8.0]

**Comment by williamw2** [comment] 2022-05-27 18:19
@mafei1982 
After digging into this a bit it looks like "onfocusout" is the preferred method for handling the loss of focus on the FluentUI web components. Will this work for your scenario?

```
<FluentTextField @onfocusout="()=>HandleBlur()"></FluentTextField>
@code {
    void HandleBlur()
    {
        Console.WriteLine("blur");
    }
}
```

**Comment by williamw2** [comment] 2022-06-06 17:06
Closing as this appears to be the expected behavior.

**Closed by williamw2** 2022-06-06 17:06 UTC
Labels: area:fast-blazor
