### ISSUE TITLE
feat: 'Trim' the number of icon `.svg` files when publishing the app, only publish those which are in use by the app.

### ISSUE THREAD

**Issue by JeepNL** [microsoft/fast-blazor#225] opened 2022-09-18 18:04 UTC
# 🙋 Feature Request

'Trim' the number of icon `.svg` files when publishing the app, only publish those which are in use by the app. Currently all 12.000+ icon files are published to the `wwwroot\_content\Microsoft.Fast.Components.FluentUI\icons` directory

I'm using Cloudflare to publish my Blazor WASM front-end and it takes a long time to deploy it because of the number of icon files. And it's using MB's I rather use for something else. Cloudflare has a limit of 25MB. 

A possible solution (for now) is to keep track of which icons I'm using, and delete the rest from the icon directory after publishing.

**Comment by vnbaaij** [comment] 2022-09-18 18:12
The way it is set up is that all the icons are included in the dll. Only the ones that are used, are download on demand. As it is one dll, deployment should not take long. The dll is only a little over 6Mb.
There is no way how we can determine which ones are being used and/or how we could trim the dll.

**Comment by JeepNL** [comment] 2022-09-18 18:33
When I do a publish the icon files are published in a folder.

![Screenshot 2022-09-18 202902](https://user-images.githubusercontent.com/39458532/190922850-e256ed91-3b03-4274-8b3e-57c822123b44.png)

But I can delete the icon folder and its sub dirs and still use them in my app?

**Comment by JeepNL** [comment] 2022-09-18 18:36
I think the _content folder does exist, this file is in it too: `Microsoft.Fast.Components.FluentUI.lib.module.js`

![Screenshot 2022-09-18 203504](https://user-images.githubusercontent.com/39458532/190923016-f29e6ad2-0914-4d1b-b508-1bbbfd712462.png)

**Comment by JeepNL** [comment] 2022-09-18 18:45
This is the publish command I use:

```
dotnet publish Client.FluentUI.csproj --nologo --force -c Release --arch x64 --os linux --self-contained true -o C:\X\Repos\Flater\_CloudflarePublish
```

and this is the `PropertyGroup` in de `.csproj` file

```
  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <PublishTrimmed>true</PublishTrimmed>
    <LangVersion>preview</LangVersion>
    <AnalysisLevel>latest-Recommended</AnalysisLevel>
    <EnablePackageValidation>true</EnablePackageValidation>
    <BlazorEnableTimeZoneSupport>true</BlazorEnableTimeZoneSupport>
    <InvariantGlobalization>true</InvariantGlobalization>
    <BlazorWebAssemblyPreserveCollationData>false</BlazorWebAssemblyPreserveCollationData>
    <TrimmerRemoveSymbols>true</TrimmerRemoveSymbols>
    <DebuggerSupport>false</DebuggerSupport>
    <!--<ServiceWorkerAssetsManifest>service-worker-assets.js</ServiceWorkerAssetsManifest>-->
  </PropertyGroup>
```

**Comment by JeepNL** [comment] 2022-09-18 18:48
I can't find a `.dll` of 6 MB anywhere in the publish dir.

This sorted by size.

![Screenshot 2022-09-18 204818](https://user-images.githubusercontent.com/39458532/190923566-e1059668-001a-44b3-9d04-5c2ba6bef69d.png)

**Comment by JeepNL** [comment] 2022-09-18 18:56
Oh, I forgot to mention which versions I'm using

.NET 7 RC 1
Microsoft.Fast.Components.FluentUI 1.6.0-rc.1

**Comment by JeepNL** [comment] 2022-09-18 19:02
The individual icon files are published to the `_content` directory of you demo site https://aka.ms/fluentui-blazor too.

see: https://brave-cliff-0c0c93310.azurestaticapps.net/_content/Microsoft.Fast.Components.FluentUI/icons/Accessibility/accessibility_16_filled.svg

**Comment by vnbaaij** [comment] 2022-09-18 21:22
Ok, apparently I did not understand the publish process that good...You are correct everything gets published to the _content folder and this is by design. It doesn't matter which .NET version you are using here. .NET 6 and .NET 7 work alike in this regards.

What I wrote before is right too. All the icons are part of the Fluent UI package and are stored in the DLL. If you check the size of the DLL in the package, you'll see it's about 6.5Mb.

As said, there is no way how to determine which icons are being used without something hooking into the publish process and scan all the code. Tracking them manually and deleting the ones not used is is an option, I suppose. But I'm afraid you're on your own there. It is not (and most probably will not ever be) part of the library. 

With regards to the storage size, maybe you can take a look at Azure Static Web Apps? The free tier gives you 250MB per app...

I'm closing this as not planned because, as I explained, we can't change the way this process works.

**Closed by vnbaaij** 2022-09-18 21:22 UTC

**Comment by JeepNL** [comment] 2022-09-19 08:49
I can't find that 6.5MB `.dll` file in the publish dir? What's its name?

**Comment by vnbaaij** [comment] 2022-09-19 08:57
It is the `Microsoft.Fast.Components.FluentUI.dll` file. It is in the publish dir but at a much smaller size. In the package you add with NuGet it is about 6.5 MB.

The publish process extracts the static assets from the DLL and puts them in the `wwwroot/_content/Microsoft.Fast.Components.FluentUI/...` structure. The DLL that remains (with the actual code) is the about 900K `Microsoft.Fast.Components.FluentUI.dll` file you see.

**Comment by JeepNL** [comment] 2022-09-19 09:29
Okay, so the icon files are not contained in the `.dll` file (_after publish_. But that's good, because in that case I can 'trim' the `_content` dir manually. (_By keeping track of which icon files I use_)

I know MudBlazor (another component library) did find a solution to trim the number of icon ` svg ` (_I believe_) files when publishing, with the default trim/linker option. So, not with additional code. But I have to look at it again to be sure, and figure out what they are doing.
