### ISSUE TITLE
fix: non-reactive FluentWizard

### ISSUE THREAD

**Issue by RichardSquires** [microsoft/fast-blazor#1487] opened 2024-02-09 14:34 UTC
# 🐛 Bug Report

Using a project the template, with a new razor page using the demo of the FluentWizard control does not reactive to user input.

## 💻 Repro or Code Sample

1. Setup a project from the template "Fluent Blazor Web App"
2. Use the defaults for the creation (.Net 8.0, Auth type none, server side render mode with samples included
3. Copy the code from the first example code here: https://www.fluentui-blazor.net/Wizard
4. Create a new razor component (I called it Wizard.razor)
5. Add a new page decoration `@page "/wizard"`
6. Comment out the line in "OnStepChange" method calling "DemoLogger.WriteLine" (this was causing a build error for me)
7. Run the application
8. Navigate to the page "/Wizard"
9. Attempt to click next

## 🤔 Expected Behavior

Able to switch between top and bottom Steps positions and click the next button to through the steps as per the demo site.

## 😯 Current Behavior

The switcher changes but the "FluentWizard" control does not change

## 💁 Possible Solution

🤷‍♀️

## 🔦 Context

Learn and understand Fluent UI for Blazor

## 🌍 Your Environment

* OS & Device: Windows 10
* Browser: Microsoft Edge, Google Chrome, Mozilla FireFox
* .NET and FAST Version: default from latest template, .Net 8 & Microsoft.FluentUI.AspNetCore.Components 4.4.2-preview.24040.1 (also tested 4.4.1)

**Comment by vnbaaij** [comment] 2024-02-09 14:40
Hi, (and welcome)

This is not a bug. You choose to use SSR. In that mode, most of our components will only be displayed. For them to work, interactivity is needed so a rendermode on the app, page or component must be supplied.
This is mentioned in the docs as well...

Closing this as not actionable.

**Closed as not planned** 2024-02-09 14:41 UTC
Labels: closed:not-actionable
